# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: app
disk: 1024
type: "python:2.7"

dependencies:
    python:
       pipenv: '*'

hooks:
    build: |
      pipenv install --system
relationships:
    mysql: "mysql:mysql"
    redis: "redis:redis"

web:
    commands:
        start: python server.py
