name: app
disk: 1024
type: "python:2.7"

dependencies:
    python:
       pipenv: '*'

hooks:
    build: |
      pipenv install --system
relationships:
    mysql: "mysql:mysql"
    redis: "redis:redis"

web:
    commands:
        start: python server.py
