
name: app

disk: 1024

type: "python:2.7"

hooks:
    build: |
        pip install -r requirements.pinned.txt

relationships:
    mysql: "mysql:mysql"
    redis: "redis:redis"

web:
    commands:
        start: python server.py
